version: '3.8'

services:
  backend:
    build: .
    container_name: fastapi_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - legatoo-network

networks:
  legatoo-network:
    driver: bridge
